# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/draft.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protocol/draft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protocol/draft.proto\x12\nspecextend\"\xff\x01\n\x0c\x44raftRequest\x12\x17\n\x0f\x64raft_token_ids\x18\x01 \x03(\x05\x12\x14\n\x0cposition_ids\x18\x02 \x03(\x05\x12\x1b\n\x13tree_attention_mask\x18\x03 \x01(\x0c\x12\x16\n\x0etree_mask_rows\x18\x04 \x01(\x05\x12\x16\n\x0etree_mask_cols\x18\x05 \x01(\x05\x12\x17\n\x0f\x63urrent_seq_len\x18\x06 \x01(\x05\x12\x19\n\x11request_retrieval\x18\x07 \x01(\x08\x12\x10\n\x08timestep\x18\x08 \x01(\x05\x12\x13\n\x0bparent_last\x18\t \x03(\x05\x12\x18\n\x10prefix_token_ids\x18\n \x03(\x05\"\xb7\x01\n\x0cVerifyResult\x12\x1a\n\x12\x61\x63\x63\x65pted_token_ids\x18\x01 \x03(\x05\x12\x15\n\raccept_length\x18\x02 \x01(\x05\x12\x12\n\nnext_token\x18\x03 \x01(\x05\x12\x1f\n\x17retrieval_chunk_indices\x18\x04 \x03(\x05\x12\x0f\n\x07\x65victed\x18\x05 \x01(\x05\x12\x11\n\tneed_stop\x18\x06 \x01(\x08\x12\x1b\n\x13\x61\x63\x63\x65pted_parent_ids\x18\x07 \x03(\x05\x32]\n\x11SpecExtendService\x12H\n\x0eSpeculateDraft\x12\x18.specextend.DraftRequest\x1a\x18.specextend.VerifyResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.draft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRAFTREQUEST']._serialized_start=37
  _globals['_DRAFTREQUEST']._serialized_end=292
  _globals['_VERIFYRESULT']._serialized_start=295
  _globals['_VERIFYRESULT']._serialized_end=478
  _globals['_SPECEXTENDSERVICE']._serialized_start=480
  _globals['_SPECEXTENDSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
